#!/usr/bin/env python3
import os
import subprocess

input_folder = './public/app/themes/originals'
output_folder = './public/app/themes'

files = os.listdir(input_folder)

for entry in files:
    filename, fileext = os.path.splitext(entry)

    input_filepath = os.path.join(input_folder, entry)
    thumbnail_output_filepath = os.path.join(output_folder, filename + '_thumb.jpg')
    fullsize_output_filepath = os.path.join(output_folder, filename + '.jpg')

    print('process ' + input_filepath)

    useHighQuality = filename.startswith('ray') or filename.startswith('shine') or filename.startswith('aqua')
    quality = '85' if useHighQuality else '40'

    thumbnails_magick_command = ['magick', 'convert', input_filepath, '-resize', '200', '-quality', quality,
                                 thumbnail_output_filepath]
    subprocess.run(thumbnails_magick_command)

    fullsize_magick_command = ['magick', 'convert', input_filepath, '-resize', '2000', '-quality', quality,
                               fullsize_output_filepath]
    subprocess.run(fullsize_magick_command)
